import type { Metadata } from "next";
import "./globals.css";
import Button from './components/Button';

export const metadata: Metadata = {
  title: "Dnd Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Button link='/plan/new' text='新規プラン作成' />
        </header>
        {children}
      </body>
    </html>
  );
}
